name: GitHub Actions

on: [ push ]

jobs:
  build:

    strategy:
      matrix:
        php-versions: [ 7.4 ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "{dir}={$(composer config cache-files-dir)}" >> $GITHUB_OUTPUT

      - name: Setup Composer caching
        uses: actions/cache@v3
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Run code sniffer
        run: composer cs

      - name: Run phpunit tests
        run: composer unit
