name: GitHub Actions

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04 # PHP version 7.4.
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: WPCS validate
        run: composer cs

      - name: Tests
        run: composer unit
