name: GitHub Actions

on: [ push ]

jobs:
  build:

    strategy:
      matrix:
        php-versions: [ 7.4 ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Setup Composer caching
        uses: ramsey/composer-install@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Run code sniffer
        run: composer cs

      - name: Run phpunit tests
        run: composer unit
