name: GitHub Actions

on: [ push ]

jobs:
  build:

    strategy:
      matrix:
        php-versions: [ 7.4 ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: pecl
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: WPCS validate
        run: composer cs

      - name: Tests
        run: composer unit
